cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add_cart, name='add_cart'),
    path('list/', views.list, name='list'),
    path('list/remove', views.remove, name='remove'),
]

eBazar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('sellers/', include('sellers.urls')),
    path('account/', include('accounts.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from product.models import Product
from .cart import Cart
from cart import cart

# Create your views here.
def add_cart(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        productId = request.POST.get('productId')
        quantity = int(request.POST.get('quantity'))
        product = get_object_or_404(Product, id = productId)
        cart.add(product, quantity)
        return JsonResponse({'quantity':cart.__len__()})
    return JsonResponse({'ok':'ok'})


def list(request):
    cart = Cart(request)
    return render(request, 'cart/list.html', {'cart':cart})


def remove(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        productId = request.POST.get('productid')
        cart.remove(productId)

        return JsonResponse({
            'final_price':cart.final_price(),
            'total_price':cart.get_total_price(),
            'product_numbers':cart.products(),
            'quantity':cart.__len__(),
            })

templates/cart/list.html
{% extends 'core/base.html' %}
{% block content %}
<section class="h-100 h-custom" style="background-color: #0000;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-10">
        <div class="col-12">
          <div class="card card-registration card-registration-2" style="border-radius: 15px;">
            <div class="card-body p-0">
              <div class="row g-0">
                <div class="col-lg-8">
                  <div class="p-5">
                    <div class="d-flex justify-content-between align-items-center mb-5">
                      <h1 class="fw-bold mb-0 text-black">Shopping Cart</h1>
                      <h6 class="mb-0 text-muted">{{ cart|length }} items</h6>
                    </div>
                    <hr class="my-4">


                    {% for item in cart %}
                    <div class="row mb-4 d-flex justify-content-between align-items-center product-item" data-index="{{item.product.id}}">
                      <div class="col-md-2 col-lg-2 col-xl-2">
                        <img
                          src="{{item.product.image.url}}"
                          class="img-fluid rounded-3" alt="Cotton T-shirt">
                      </div>
                      <div class="col-md-3 col-lg-3 col-xl-3">
                        <h6 class="text-muted">{{item.product.sub_cate.name}}</h6>
                        <h6 class="text-black mb-0">{{item.product.name}}</h6>
                      </div>
                      <div class="col-md-3 col-lg-3 col-xl-2 d-flex">
                        <button class="btn btn-link px-2"
                          onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                          <i class="fas fa-minus"></i>
                        </button>

                        <input id="form1" min="0" name="quantity" value="1" type="number"
                          class="form-control form-control-sm" / disabled>

                        <button class="btn btn-link px-2"
                          onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                          <i class="fas fa-plus"></i>
                        </button>
                      </div>
                      <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                        <strong class="mb-0">{{ item.quantity }} x {{item.product.price}}</strong>
                        <h6 class="mb-0">BDT {{ item.sub_total }}</h6>
                      </div>
                      <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                        <button type="button" id="delete-button" data-index="{{item.product.id}}" class="btn btn-outline-secondary btn-sm delete-button"><i class="fas fa-times"></i></button>
                      </div>
                      <hr class="my-4">
                    </div>

                    {% endfor %}


                    <div class="pt-5">
                      <h6 class="mb-0"><a href="{% url 'home' %}" class="text-body"><i
                            class="fas fa-long-arrow-alt-left me-2"></i>Back to shop</a></h6>
                    </div>
                  </div>
                </div>
                <div class="col-lg-4 bg-grey">
                  <div class="p-5">
                    <h3 class="fw-bold mb-5 mt-2 pt-1">Summary</h3>
                    <hr class="my-4">

                    <div class="d-flex justify-content-between mb-4">
                      <h5 class="text-uppercase">Number of Products: </h5>
                      <h5 id="product-numbers">{{cart.products}}</h5>
                    </div>

                    <div class="d-flex justify-content-between mb-4">
                      <h5 class="text-uppercase">Sub Total: </h5>
                      <h5 id="total-price">BDT {{ cart.get_total_price }}tk</h5>
                    </div>

                    <div class="d-flex justify-content-between mb-4">
                      <h5 class="text-uppercase">Delivery Cost: </h5>
                      <h5>BDT 50tk</h5>
                    </div>

                    <hr>

                    <div class="d-flex justify-content-between mb-5">
                      <h5 class="text-uppercase">Total price</h5>
                      <h5 id="final-price">BDT {{cart.final_price}}tk</h5>
                    </div>

                    <a class="btn btn-dark btn-lg" href={% url 'order-add' %}>Make A Order</a>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div class="p-md-2"></div>

  <script>

  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',
      url: '{% url 'cart:remove' %}',
      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("product-numbers").innerHTML = json.product_numbers;
        document.getElementById("total-price").innerHTML = json.total_price
        document.getElementById("final-price").innerHTML = json.final_price
        document.getElementById("cart-quantity").innerHTML = json.quantity
      },
      error: function (xhr, errmsg, err) {}
    });
  })


  </script>
{% endblock content %}