accounts/urls.py
from django.urls import path, re_path
from .views import AccountView, logout_view, login_view

app_name = 'Account'

urlpatterns = [
    path('<str:slug>', AccountView.as_view(), name='profile'),
    path('logging-out', logout_view, name='logout'),
    path('log-in/', login_view, name='login-view')
]

cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add_cart, name='add_cart'),
    path('list/', views.list, name='list'),
    path('list/remove', views.remove, name='remove'),
]

eBazar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('sellers/', include('sellers.urls')),
    path('account/', include('accounts.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/core/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE HTML>
<html lang="en">
<head>

  	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  	<meta name="description" content="Type some info">
  	<meta name="author" content="Type name">

  	<title>eBazarBD | Organic Store</title>

  	<!-- Bootstrap css -->
  	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

  	<!-- Custom css -->
  	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/myStyle.css' %}">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.css' %}">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
  	<link rel="stylesheet" type="text/css" href="{% static 'css/auth/login.css' %}">

  	<!-- Font awesome 5 -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>

	<!-- Jquery -->
  	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</head>
<body class="bg-light">

<header class="section-header">
	<section class="header-main bg-white">
		<div class="container">
			<div class="row gy-3 align-items-center">
				<div class="col-lg-2 col-sm-4 col-4">
					<a href={% url 'home' %} class="navbar-brand">
						<!-- <img class="logo" height="40" src="images/logo.svg"> -->
            <strong class="h3">eBazarBD</strong>
					</a> <!-- brand end.// -->
				</div>
				<div class="order-lg-last col-lg-5 col-sm-8 col-8">
					<div class="float-end">
						{% if request.user.is_authenticated %}
						<a href={% url 'Account:profile' request.user.slug %} class="btn btn-light">
						    <i class="fa fa-user"></i>  <span class="ms-1 d-none d-sm-inline-block"> {{ request.user.username }} </span>
						</a>
						{% else %}
						<a href={% url 'Account:login-view' %} class="btn btn-light">
						    <i class="fa fa-user"></i>  <span class="ms-1 d-none d-sm-inline-block"> Sign in  </span>
						</a>
						{% endif %}
						<a href="#" class="btn btn-light">
							<i class="fa fa-heart"></i>  <span class="ms-1 d-none d-sm-inline-block">Wishlist</span>
						</a>
						<a href={% url 'cart:list' %} class="btn btn-light">
							<i class="fa fa-shopping-cart"></i>
							<span class="ms-1">
								{% with total_qty=cart|length %}
									<div class="d-inline-flex" id="cart-quantity">
								  		{% if total_qty > 0 %}
											{{ total_qty }}
								  		{% else %}
											0
								  		{% endif %}
									</div>
								{% endwith %}
							</span>
						</a>
			        </div>
				</div> <!-- col end.// -->
				<!-- Search Option Starts -->

				{% include "core/search.html" %}

				<!-- Search Option Ends -->
			</div> <!-- row end.// -->
		</div> <!-- container end.// -->
	</section> <!-- header-main end.// -->

	<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
		<div class="container">
			<button class="navbar-toggler border" type="button" data-bs-toggle="collapse" data-bs-target="#navbar_main" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbar_main">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a class="nav-link ps-0" href="{% url 'home' %}"> Home </a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="#">Hot offers</a>
					</li>

					{% for category in categories %}

					<li class="nav-item dropdown">
						<a class="dropdown-toggle nav-link" href="#" data-bs-toggle="dropdown">
							{{ category.name }}
						</a>
						<ul class="dropdown-menu">
							<li> <a class="dropdown-item" href="#"> All </a> </li>
							{% for item in category.sub_category.all %}
								<li> <a class="dropdown-item" href= {%url 'list-view' item.id %} > {{ item.name }} </a> </li>
							{% endfor %}
						</ul>
					</li>
					{% endfor %}
				</ul>
			</div> <!-- collapse end.// -->
		</div> <!-- container end.// -->
	</nav> <!-- navbar end.// -->
</header> <!-- section-header end.// -->



{% block content %}

{% endblock content %}


<footer class="section-footer bg-primary footer-dark">
<div class="container">
  <section class="footer-main padding-y">
    <div class="row">
      <aside class="col-12 col-sm-12 col-lg-3">
        <article class="me-lg-4">
          <strong>eBazarBD</strong>
          <p class="mt-3"> © {% now "Y" %}  All rights reserved. </p>
        </article>
      </aside>
      <aside class="col-6 col-sm-4 col-lg-2">
        <h6 class="title">Store</h6>
        <ul class="list-menu">
          <li> <a href="#">About us</a></li>
          <li> <a href="#">Find store</a></li>
          <li> <a href="#">Categories</a></li>
          <li> <a href="#">Blogs</a></li>
        </ul>
      </aside>
      <aside class="col-6 col-sm-4 col-lg-2">
        <h6 class="title">Information</h6>
        <ul class="list-menu">
          <li> <a href="#">Help center</a></li>
          <li> <a href="#">Money refund</a></li>
          <li> <a href="#">Shipping info</a></li>
          <li> <a href="#">Refunds</a></li>
        </ul>
      </aside>
      <aside class="col-6 col-sm-4  col-lg-2">
        <h6 class="title">Support</h6>
        <ul class="list-menu">
          <li> <a href="#"> Help center </a></li>
          <li> <a href="#"> Documents </a></li>
          <li> <a href="#"> Account restore </a></li>
          <li> <a href="#"> My Orders </a></li>
        </ul>
      </aside>
      <aside class="col-12 col-sm-12 col-lg-3">
        <h6 class="title">Newsletter</h6>
        <p>Stay in touch with latest updates about our products and offers </p>

        <form class="mb-3">
          <div class="input-group">
            <input class="form-control" type="text" placeholder="Email">
            <button class="btn btn-light" type="submit">
              Join
            </button>
          </div> <!-- input-group.// -->
        </form>
      </aside>
    </div> <!-- row.// -->
  </section>  <!-- footer-top.// -->
  <hr class="my-0">

</div> <!-- container end.// -->
</footer>


<!-- Bootstrap js -->
<script src={% static 'js/bootstrap.js' %}></script>

<!-- Custom js -->
<script src= {% static 'js/style.js' %}></script>
<script src= {% static 'js/cart.js' %}></script>

<!-- jquery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

</body>
</html>

templates/core/search.html
<div class="col-lg-5 col-md-12 col-12">
    <form action={% url 'search' %} method="get" class="">
      <div class="input-group">
        <input type="search" class="form-control" name="search" style="width:55%" placeholder="Search">
        <button class="btn btn-dark">
          <i class="fa fa-search"></i>
        </button>
      </div> <!-- input-group end.// -->
    </form>
</div> <!-- col end.// -->