cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add_cart, name='add_cart'),
    path('list/', views.list, name='list'),
    path('list/remove', views.remove, name='remove'),
]

eBazar/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('sellers/', include('sellers.urls')),
    path('account/', include('accounts.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from product import views

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-details'),
    path('products/list/<int:pk>', views.ProductListView.as_view(), name='list-view'),
    path('products/list/', views.ProductListView.as_view(), name='list-view'),
    path('product/', views.ProductListView.as_view(), name='search'),
]

product/models.py
from sellers.models import Seller
from django.conf import settings
from django.utils import timezone
from django.db import models

from PIL import Image



class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"


class SubCategory(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='sub_category')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Sub_Category"
        verbose_name_plural = "Sub_Categories"




class Brand(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name



class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    discount = models.FloatField()
    image = models.ImageField(upload_to = 'products', blank = True, null = True)
    sub_cate = models.ForeignKey(SubCategory, on_delete=models.CASCADE, blank=True, null=True)
    brand_name = models.ForeignKey(Brand, on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(Seller, on_delete=models.CASCADE)

    visited = models.IntegerField(default = 0)
    last_visit = models.DateTimeField(auto_now=True)
    total_sold = models.IntegerField(default=0)
    total_returned = models.IntegerField(default=0)
    refundable = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    @property
    def total_earning(self):
        return self.total_sold * self.price

    def countVisitor(self):
        self.visited += 1
        self.save()

    def totalSold(self, quantity):
        self.total_sold += quantity
        self.save()

    def totalReturned(self):
        self.total_returned += 1
        self.save()

    def save(self):
        super().save()

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

product/views.py
from django.views.generic import DetailView, ListView
from django.db.models import Q
from django.shortcuts import render
from product import models

from product.models import Product

def home(request):
    product = {
        'products':Product.objects.all().order_by('-id')[:4],
        'fav_items':Product.objects.all().order_by('-visited')[:6]
    }
    return render(request, 'product/index.html', product)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'product/details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'].countVisitor()
        context["products"] = Product.objects.all().order_by('-last_visit')[:4]
        return context


class ProductListView(ListView):
    model = Product
    template_name = 'product/list.html'
    context_object_name = 'products'
    ordering = ['-created_by']

    def get_queryset(self):
        if self.kwargs.get('pk'):
            return models.Product.objects.filter(sub_cate = self.kwargs.get('pk'))

        if self.request.method == "GET":
            lookups = Q(name__contains  = self.request.GET.get('search')) | Q(price__contains  = self.request.GET.get('search'))
            return models.Product.objects.filter(lookups)

        else:
            return models.Product.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["searched_for"] = self.request.GET.get('search')
        return context

templates/product/details.html
{% extends 'core/base.html' %}
{% block content %}
<div class="mt-3 p-md-3">
    <section class="padding-y">
        <div class="container">

        <div class="row">
        <aside class="col-lg-6">
          <article class="gallery-wrap">
            <div class="img-big-wrap img-thumbnail">
               <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big.jpg">
                  <img height="560" src={{ object.image.url }}>
               </a>
            </div> <!-- img-big-wrap.// -->
          </article> <!-- gallery-wrap .end// -->
        </aside>
        <main class="col-lg-6">
          <article class="ps-lg-3">
            <h4 class="title text-dark"> {{ object.name }} </h4>
            <div class="mb-3">
              <var class="price h5">BDT {{object.price}}</var>
              <span class="text-muted">/per box</span>
            </div>

            <p>Modern look and quality demo item is a streetwear-inspired collection that continues to break away from the conventions of mainstream fashion. Made in Italy, these black and brown clothing low-top shirts for men.</p>

            <dl class="row">
              <dt class="col-3">Type:</dt>
              <dd class="col-9">Regular</dd>

              <dt class="col-3">Color</dt>
              <dd class="col-9">Brown</dd>

              <dt class="col-3">Material</dt>
              <dd class="col-9">Cotton, Jeans </dd>

              <dt class="col-3">Brand</dt>
              <dd class="col-9">Reebook </dd>
            </dl>

            <hr>

            <div class="row mb-4">
              <div class="col-md-4 col-6 mb-2">
                <label class="form-label">Size</label>
                <select class="form-select">
                  <option>Small</option>
                  <option>Medium</option>
                  <option>Large</option>
                </select>
              </div> <!-- col.// -->
              <div class="col-md-4 col-6 mb-3">
                <label class="form-label d-block">Quantity</label>
                <div class="input-group input-spinner">
                  <button class="btn btn-icon btn-light" type="button">
                      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#999" viewBox="0 0 24 24">
                        <path d="M19 13H5v-2h14v2z"></path>
                      </svg>
                  </button>
                  <input name = "quantity" id="quantity" class="form-control text-center" placeholder="" value="1" required>
                  <button class="btn btn-icon btn-light" type="button">
                      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="#999" viewBox="0 0 24 24">
                        <path d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"></path>
                      </svg>
                  </button>
                </div> <!-- input-group.// -->
              </div> <!-- col.// -->
            </div> <!-- row.// -->

            <button class="btn btn-dark btn-lg btn-block" style="width: 100% !important;" id="add-cart" value="{{product.id}}"> <i class="me-1 fa fa-shopping-basket"></i> Add to cart </button>

          </article> <!-- product-info-aside .// -->
        </main> <!-- col.// -->
        </div> <!-- row.// -->

        </div> <!-- container .//  -->
        </section>
</div>
<div class="container">
    <!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial;}

/* Style the tab */
.tab {
  overflow: hidden;
  border: 1px solid #ccc;
  background-color: #f1f1f1;
}

/* Style the buttons inside the tab */
.tab button {
  background-color: inherit;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  transition: 0.3s;
  font-size: 17px;
}

/* Change background color of buttons on hover */
.tab button:hover {
  background-color: #ddd;
}

/* Create an active/current tablink class */
.tab button.active {
  background-color: #ccc;
}

/* Style the tab content */
.tabcontent {
  display: none;
  padding: 6px 12px;
  border: 1px solid #ccc;
  border-top: none;
}
</style>
</head>
<body>

<h2>Product Informations</h2>

<div class="tab p-md-3">
  <button class="tablinks" onclick="openCity(event, 'London')">London</button>
  <button class="tablinks" onclick="openCity(event, 'Paris')">Paris</button>
  <button class="tablinks" onclick="openCity(event, 'Tokyo')">Tokyo</button>
</div>

<div id="London" class="tabcontent">
  <h3>London</h3>
  <p>London is the capital city of England.</p>
</div>

<div id="Paris" class="tabcontent">
  <h3>Paris</h3>
  <p>Paris is the capital of France.</p>
</div>

<div id="Tokyo" class="tabcontent">
  <h3>Tokyo</h3>
  <p>Tokyo is the capital of Japan.</p>
</div>
<div class="pt-3"></div>
<script>
function openCity(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

</body>
</html>

</div>
<section class="padding-top">
    <div class="container">

        <header class="section-heading">
            <h3 class="section-title">Recently viewed</h3>
        </header>

        <div class="row">

          {% for product in products %}

          <div class="col-lg-3 col-md-6 col-sm-6">

            <figure class="card card-product-grid">
              <a href={% url 'product-details' product.id %}>
                <div class="img-wrap">
                  <img src={{ product.image.url}}>
                </div>
              </a>
              <figcaption class="info-wrap border-top">
                <div class="price-wrap">
                  <span class="price">BDT {{ product.price }}</span>
                </div> <!-- price-wrap.// -->
                <p class="title mb-2 h5">{{ product.name }}</p>

                <a href={% url 'product-details' product.id %} class="btn btn-dark btn-lg btn-block" style="width: 100% !important;">Select Options</a>
              </figcaption>
            </figure>
          </div>

          {% endfor %}

    </div> <!-- container end.// -->
    </section>
    <div class="pt-3"></div>

    <script>
      $(document).on('click', '#add-cart', function (e) {
          e.preventDefault();
          $.ajax({
              type: 'POST',
              url: "{% url 'cart:add_cart' %}",
              data: {
                productId: $('#add-cart').val(),
                quantity: $('#quantity').val(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function(json){
              document.getElementById('cart-quantity').innerHTML = json.quantity,
              console.log( json.quantity)
            }
          })
      })
    </script>
{% endblock content %}

templates/product/index.html
{% extends 'core/base.html' %}
{% block content %}




<!-- ================ SECTION INTRO ================ -->
<section class="section-intro padding-top-sm">
	<div class="container">
	<main class="card p-3">
		<div class="row">
			<aside class="col-lg-3">
				<nav class="nav flex-column nav-pills overflow">
          <div class="scrollbar scrollbar-primary">
            <div class="force-overflow">
              {% for category in categories %}
              <a class="nav-link" href="#">{{category.name}}</a>
              {% endfor %}
            </div>
          </div>
				</nav>

			</aside>

			<div class="col-lg-9" style="height: 300 !important;">
				<div class=" bg-white rounded">
          <img class="d-block w-100" height="50%" src="https://drive.google.com/uc?export=view&id=1vZT8peUEWOQ4lwZPXOu1l7sMJw9Ve1bn" alt="First slide">
        </div>
			</div>
		</div>
	</main>
	</div> <!-- container end.// -->
</section>
<!-- ================ SECTION INTRO END.// ================ -->

<!-- ================ SECTION PRODUCTS ================ -->
<section class="padding-top">
  <div class="container">

    <header class="section-heading">
      <h3 class="section-title">New Arrivals</h3>
    </header>

    <div class="row">

      {% for product in products %}

      <div class="col-lg-3 col-md-6 col-sm-6">
        <figure class="card card-product-grid">
          <a href={% url 'product-details' product.id %}>
            <div class="img-wrap">
              <img src={{ product.image.url}}>
            </div>
          </a>
          <figcaption class="info-wrap border-top">
            <div class="price-wrap">
              <span class="price">BDT {{ product.price }}</span>
            </div> <!-- price-wrap.// -->
            <p class="title mb-2 h5">{{ product.name }}</p>
            <a href={% url 'product-details' product.id %} class="btn btn-dark btn-lg btn-block" style="width: 100% !important;">Select Options</a>
          </figcaption>

        </figure>
      </div>

      {% endfor %}

    </div> <!-- row end.// -->

  </div> <!-- container end.// -->
  </section>
  <!-- ================ SECTION PRODUCTS END.// ================ -->


  <!-- ================ SECTION FEATURE ================ -->
  <section class="padding-top">
  <div class="container">
    <div class="row gy-4">
      <aside class="col-lg-6">
        <article class="card-banner bg-gray h-100" style="min-height: 200px">
          <div class="p-3 p-lg-5"  style="max-width:70%">
            <h3> Best products & brands</h3>
            <p>That's true but not always</p>
            <a class="btn btn-dark" href="#"> Claim offer </a>
          </div>
          <img src="https://drive.google.com/uc?export=view&id=11R6zI1rpexrUixo6LgG5aHf_N0xkXrhJ" height="250" class="img-bg">
        </article>
      </aside> <!-- col.// -->
      <div class="col-6">
        <aside class="">
          <article class="card-banner bg-gray h-100" style="min-height: 200px">
            <div class="p-3 p-lg-5"  style="max-width:70%">
              <h3> Best products & brands</h3>
              <p>That's true but not always</p>
              <a class="btn btn-dark" href="#"> Claim offer </a>
            </div>
            <img src="https://drive.google.com/uc?export=view&id=11R6zI1rpexrUixo6LgG5aHf_N0xkXrhJ" height="250" class="img-bg">
          </article>
        </aside> <!-- col.// -->
      </div>
    </div> <!-- row.// -->
  </div> <!-- container end.// -->
  </section>
  <!-- ================ SECTION FEATURE END.// ================ -->

  <!-- ================ SECTION PRODUCTS ================ -->
  <section class="padding-top">
  <div class="container">

    <header class="section-heading">
      <h3 class="section-title">Popular Products</h3>
    </header>

    <div class="row gy-3">
      {% for item in fav_items %}
      <div class="col-lg-2 col-md-4 col-4">
        <a href={% url 'product-details' item.id %} class="img-wrap">
          <img height="200" width="200" class="img-thumbnail" src={{ item.image.url}}>
        </a>
      </div> <!-- col.// -->
      {% endfor %}
    </div> <!-- row end.// -->

  </div> <!-- container end.// -->
  </section>
  <!-- ================ SECTION PRODUCTS END.// ================ -->

  <br>

{% endblock content %}

templates/product/list.html
{% extends "core/base.html" %}
{% block content %}

<section class="padding-y">
    <div class="container">

    <div class="row">
        <aside class="col-lg-3">

    <button class="btn btn-outline-secondary mb-3 w-100 d-lg-none collapsed" data-bs-toggle="collapse" data-bs-target="#aside_filter" aria-expanded="false">Show filter</button>

    <!-- ===== Card for sidebar filter ===== -->
    <div id="aside_filter" class="card d-lg-block mb-5 collapse">

      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title collapsed" data-bs-toggle="collapse" data-bs-target="#collapse_aside1" aria-expanded="false">
            <i class="icon-control fa fa-chevron-down"></i>   Related items
          </a>
        </header>
        <div class="collapse" id="collapse_aside1">
          <div class="card-body">
            <ul class="list-menu">
              <li><a href="#">Electronics </a></li>
              <li><a href="#">Accessories  </a></li>
              <li><a href="#">Home items </a></li>
              <li><a href="#">Men's clothing </a></li>
              <li><a href="#">Interior items </a></li>
              <li><a href="#">Magazines </a></li>
              <li><a href="#">Category name </a></li>
              <li><a href="#">Home items </a></li>
            </ul>
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article> <!-- filter-group // -->

      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title collapsed" data-bs-toggle="collapse" data-bs-target="#collapse_aside_brands" aria-expanded="false">
            <i class="icon-control fa fa-chevron-down"></i>  Brands
          </a>
        </header>
        <div class="collapse" id="collapse_aside_brands" >
          <div class="card-body">
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Mercedes </span>
                <b class="badge rounded-pill bg-gray-dark float-end">120</b>
              </label> <!-- form-check end.// -->

              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Toyota </span>
                <b class="badge rounded-pill bg-gray-dark float-end">15</b>
              </label> <!-- form-check end.// -->

              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Mitsubishi </span>
                <b class="badge rounded-pill bg-gray-dark float-end">35</b>
              </label> <!-- form-check end.// -->

              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Nissan </span>
                <b class="badge rounded-pill bg-gray-dark float-end">89</b>
              </label> <!-- form-check end.// -->

              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="">
                <span class="form-check-label"> Honda </span>
                <b class="badge rounded-pill bg-gray-dark float-end">30</b>
              </label> <!-- form-check end.// -->

              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="">
                <span class="form-check-label"> Honda accord </span>
                <b class="badge rounded-pill bg-gray-dark float-end">30</b>
              </label> <!-- form-check end.// -->
          </div> <!-- card-body .// -->
        </div> <!-- collapse.// -->
      </article>

      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title collapsed" data-bs-toggle="collapse" data-bs-target="#collapse_aside2" aria-expanded="false">
            <i class="icon-control fa fa-chevron-down"></i>  Price
          </a>
        </header>
        <div class="collapse" id="collapse_aside2" >
          <div class="card-body">
            <input type="range" class="form-range" min="0" max="100">
            <div class="row mb-3">
              <div class="col-6">
                <label for="min" class="form-label">Min</label>
                <input class="form-control" id="min" placeholder="$0" type="number">
              </div> <!-- col end.// -->

              <div class="col-6">
                <label for="max" class="form-label">Max</label>
                <input class="form-control" id="max" placeholder="$1,0000" type="number">
              </div> <!-- col end.// -->
            </div> <!-- row end.// -->
            <button class="btn btn-light w-100" type="button">Apply</button>
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article> <!-- filter-group // -->

      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title collapsed" data-bs-toggle="collapse" data-bs-target="#collapse_aside3" aria-expanded="false">
            <i class="icon-control fa fa-chevron-down"></i>  Size
          </a>
        </header>
        <div class="collapse" id="collapse_aside3" >
          <div class="card-body">
              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> XS </span>
              </label>

              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> SM </span>
              </label>

              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> LG </span>
              </label>

              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> XXL </span>
              </label>
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article>  <!-- filter-group // -->

      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title collapsed" data-bs-toggle="collapse" data-bs-target="#collapse_aside4" aria-expanded="false">
            <i class="icon-control fa fa-chevron-down"></i> Ratings
          </a>
        </header>
        <div class="collapse" id="collapse_aside4">
          <div class="card-body">

              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 100%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 80%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 60%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 40%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->


          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article>  <!-- filter-group // -->

    </div> <!-- card.// -->
    <!-- ===== Card for sidebar filter .// ===== -->

        </aside> <!-- col .// -->
        <main class="col-lg-9">

        <header class="d-sm-flex align-items-center border-bottom mb-4 pb-3">
            <strong class="d-block py-2"> {{ products|length }} Items found </strong>
            <div class="ms-auto">
              {% if searched_for %}
                <strong>Showing Results for: <span class="h3" style="color: blue;">{{ searched_for }}</span> </strong>
              {% endif %}
            </div>
        </header>

        <!-- ========= content items ========= -->
        <div class="row">
          {% if products %}
            {% for product in products %}

            <div class="col-lg-3 col-md-6 col-sm-6">
              <figure class="card card-product-grid">
                <a href={% url 'product-details' product.id %}>
                  <div class="img-wrap">
                    <img src={{ product.image.url}}>
                  </div>
                </a>
                <figcaption class="info-wrap border-top">
                  <div class="price-wrap">
                    <span class="price">BDT {{ product.price }}</span>
                  </div> <!-- price-wrap.// -->
                  <p class="title mb-2 h5">{{ product.name }}</p>
                  <a href={% url 'product-details' product.id %} class="btn btn-dark btn-lg btn-block" style="width: 100% !important;">Select Options</a>
                </figcaption>

              </figure>
            </div>

            {% endfor %}
          {% else %}
          <div class="container">
            <div class="order-title-odd-23">
                <h1>Product Not Found <i class="fa-solid fa-heart-crack"></i> </h1>
                <span>Sorry We could not the product for you</span>
                <br>

                <a class="done-link-23 btn btn-dark" type="button" href= {% url 'home' %} >Home</a>
            </div>
          </div>
          {% endif %}

          </div> <!-- row end.// -->

        <hr>

          <br>

        <footer class="d-flex mt-4">
          <div>
            <a href="javascript: history.back()" class="btn btn-light"> « Go back</a>
          </div>
          <nav class="ms-3">
            <ul class="pagination">
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item active" aria-current="page">
                <span class="page-link">2</span>
              </li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#">Next</a>
              </li>
            </ul>
          </nav>
        </footer>

        <!-- ========= content items .// ========= -->



        </main> <!-- col .// -->
    </div> <!-- row .// -->

    </div> <!-- container .//  -->
    </section>

{% endblock content %}